In [1]:
import numpy as np


In [2]:
np

<module 'numpy' from 'c:\\users\\yatharth.anand\\akademize\\project 1\\.venv\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
2+3

5

In [4]:
for i in range(5):

IndentationError: expected an indented block (<ipython-input-4-aa82eeb25f1e>, line 1)

In [5]:
for in range(4):
    print(i)

SyntaxError: invalid syntax (<ipython-input-5-2b4d8a6dcdf4>, line 1)

In [6]:
for i in range(5):
    print(i)

0
1
2
3
4


In [7]:
range(5)

range(0, 5)

In [8]:
arr= np.arange(6)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
for i in arr:

IndentationError: expected an indented block (<ipython-input-10-583ba672ac35>, line 1)

In [11]:
for i in arr:
    print(i)

0
1
2
3
4
5


#Creating list of 1000 numbers

In [12]:
my_list = {}

In [13]:
my_list = {}

for i in range(5):
    my_list.append(i)
    print(my_list)

AttributeError: 'dict' object has no attribute 'append'

In [14]:
my_list = []

for i in range(5):
    my_list.append(i)
    print(my_list)

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]


#Creating a matrix

In [15]:
m_1 = [
    [1,2,3],
    [4,5,6],
    [8,9,10]
]

In [16]:
m_1

[[1, 2, 3], [4, 5, 6], [8, 9, 10]]

#given a single dimensionl list [1,2,3,4,5,6,7,8,9]
Find the multi dimentional list


In [18]:
np_m=np.rearange[1,10]
np_m

AttributeError: module 'numpy' has no attribute 'rearange'

In [19]:
np_m=np.arange[1,10]
np_m

TypeError: 'builtin_function_or_method' object is not subscriptable

In [23]:
np_m=np.arange(1,10)
np_m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np_m.reshape(2,6)

ValueError: cannot reshape array of size 11 into shape (2,6)

In [24]:
np_m.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
m1_matrix = ([1,2,3],
            [4,5,6],
             [7,8,9])
m2_matrix = np.arange(10,100,10).reshape(3,3)

In [26]:
m1_matrix

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [32]:
m2_matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [33]:
m2_matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [29]:
matrix_1 + matrix_2


NameError: name 'matrix_1' is not defined

In [34]:
m1_matrix + m2_matrix

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [45]:
m3_matrix = []
for i in range(3,27,3):
    m3_matrix.append(i)
    print(m3_matrix)

[3]
[3, 6]
[3, 6, 9]
[3, 6, 9, 12]
[3, 6, 9, 12, 15]
[3, 6, 9, 12, 15, 18]
[3, 6, 9, 12, 15, 18, 21]
[3, 6, 9, 12, 15, 18, 21, 24]
